# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: release-test

env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  -
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/aeneasr/release-test/cmd.Version={{.Tag}} -X github.com/aeneasr/release-test/cmd.Commit={{.FullCommit}} -X github.com/aeneasr/release-test/cmd.Date={{.Date}}
    binary: release-test
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - freebsd
      - linux
      - windows
      - darwin
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
  format_overrides:
    - goos: windows
      format: zip
  files:
    -  LICENSE.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brew:
  github:
    owner: aeneasr
    name: homebrew-release-test
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: hi@ory.sh

scoop:
  bucket:
    owner: aeneasr
    name: scoop-release-test
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: hi@ory.sh

dockers:
  - image_templates:
      - "arekkas/release-test:v{{ .Major }}"
      - "arekkas/release-test:v{{ .Major }}.{{ .Minor }}"
      - "arekkas/release-test:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "arekkas/release-test:{{ .Env.DOCKER_SHORT_TAG }}"
      - "arekkas/release-test:latest"
    extra_files:
      - .releaser/LICENSE.txt

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: user
    name: repo

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: true
